### ISSUE TITLE
 Показан перевод для запроса Не компилирует с абстрактными классами и Искать вместо этого перевод для Не компилируеться с абстрактными классами и It does not compile with abstract classes and boos 1.6

### ISSUE THREAD

**Issue by wodphoenix** [ybainier/Hypodermic#17]
I try to create a container for such a simple hierarchy.

#include "Hypodermic/ContainerBuilder.h"
#include "Hypodermic/Container.h"

class A
{
	public:
		
		virtual void method1()abstract;
};

class B:public A
{
	public:
		void method1() override
		{
		}
};

int main()
{
	Hypodermic::ContainerBuilder builder;
	builder.registerType<B>().asSelf().as<A>().singleInstance();
	auto container = builder.build();
	container->resolve<A>()->method1();
    return 0;
}

Use VS 2015 and boost 1.6. Got error message **error C2259: 'A': cannot instantiate abstract class**

**Comment by ybainier** [comment]
Hi,

regarding your sample, you should write something like this:

builder.registerType< B >().as< A >().singleInstance();

...

container->resolve< A >()->method1();

Cheers

**Comment by ybainier** [comment]
Hi,

regarding your sample, I think you are not writing C++, therefore the error you get is not related to _Hypodermic_. You should write something like this instead:

```cpp

class A
{
public:
    virtual ~A() {}

    virtual void method1() = 0;
};

class B : public A
{
public:
    void method1() override {}
};

Hypodermic::ContainerBuilder builder;
builder.registerType< B >().as< A >();

auto container = builder.build();

auto instanceOfBWithStaticTypeA = container->resolve< A >();
instanceOfBWithStaticTypeA->method1();
```

Cheers

**Comment by wodphoenix** [comment]
Sorry. Editor transformed template parameters 

`#include "Hypodermic/ContainerBuilder.h"
#include "Hypodermic/Container.h"

class A
{
	public:
		
		virtual void method1()abstract;
};

class B:public A
{
	public:
		void method1() override
		{
		}
};

int main()
{
	Hypodermic::ContainerBuilder builder;
	builder.registerType< B >().as< A >();
	auto container = builder.build();
	container->resolve<A>()->method1();
    return 0;
}
`
I have done as you have in the example. But I can not understand why it does not work

**Comment by ybainier** [comment]
I don't know if non native C++ is supported. Have a look at both [stackoverflow](http://stackoverflow.com/questions/1298093/can-i-use-abstract-keyword-in-c-class) and [isocpp](https://isocpp.org/wiki/faq/abcs#pure-virtual-fns) for further C++ documentation.
